language: python
python:
- '2.7'
addons:
  firefox: '30.0'
env:
  matrix:
  - DJANGO=django==1.6.8"
  - DJANGO=django==1.7.9"
install:
- pip install -r requirements.txt
script:
- python ./manage.py test --settings=pynamtest.settings.travis -v3
